In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('Advertising.csv')

In [15]:
X = df.drop('sales',axis=1)

In [16]:
df

,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9
...,...,...,...,...
195,38.2,3.7,13.8,7.6
196,94.2,4.9,8.1,9.7
197,177.0,9.3,6.4,12.8
198,283.6,42.0,66.2,25.5


In [17]:
y = df['sales']

In [18]:
from sklearn.preprocessing import PolynomialFeatures

In [19]:
Polynomial_convertor = PolynomialFeatures(degree=3, include_bias=False)

In [20]:
X

,TV,radio,newspaper
0,230.1,37.8,69.2
1,44.5,39.3,45.1
2,17.2,45.9,69.3
3,151.5,41.3,58.5
4,180.8,10.8,58.4
...,...,...,...
195,38.2,3.7,13.8
196,94.2,4.9,8.1
197,177.0,9.3,6.4
198,283.6,42.0,66.2


In [21]:
poly_features = Polynomial_convertor.fit_transform(X)

In [22]:
poly_features.shape

(200, 19)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split( poly_features, y, test_size=0.3, random_state=101)

In [25]:
X_train

array([[1.93200000e+02, 1.84000000e+01, 6.57000000e+01, ...,
        2.22433920e+04, 7.94234160e+04, 2.83593393e+05],
       [2.87600000e+02, 4.30000000e+01, 7.18000000e+01, ...,
        1.32758200e+05, 2.21675320e+05, 3.70146232e+05],
       [8.02000000e+01, 0.00000000e+00, 9.20000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 7.78688000e+02],
       ...,
       [2.39800000e+02, 4.10000000e+00, 3.69000000e+01, ...,
        6.20289000e+02, 5.58260100e+03, 5.02434090e+04],
       [2.14700000e+02, 2.40000000e+01, 4.00000000e+00, ...,
        2.30400000e+03, 3.84000000e+02, 6.40000000e+01],
       [1.63300000e+02, 3.16000000e+01, 5.29000000e+01, ...,
        5.28238240e+04, 8.84297560e+04, 1.48035889e+05]], shape=(140, 19))

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scalar = StandardScaler()

In [28]:
scalar.fit(X_train)

,copy,True
,with_mean,True
,with_std,True


In [29]:
X_train = scalar.transform(X_train) #scaling down to very less cofficience

In [30]:
X_test = scalar.transform(X_test)

In [31]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]], shape=(140, 19))

# Implementing the rigde model (L2 regression)

In [32]:
from sklearn.linear_model import Ridge

In [33]:
help(Ridge)

Help on class Ridge in module sklearn.linear_model._ridge:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(
 |      alpha=1.0,
 |      *,
 |      fit_intercept=True,
 |      copy_X=True,
 |      max_iter=None,
 |      tol=0.0001,
 |      solver='auto',
 |      positive=False,
 |      random_state=None
 |  )
 |
 |  Linear least squares with l2 regularization.
 |
 |  Minimizes the objective function::
 |
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.

In [ ]:
ridge_model = Ridge(alpha=10) #honestly we do not know that alpha is equal to 10

In [35]:
ridge_model.fit(X_train, y_train)

,alpha,10
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [36]:
test_predictions = ridge_model.predict(X_test)

In [37]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [38]:
MAE = mean_absolute_error(y_test, test_predictions)

In [39]:
MAE

0.5774404204714166

In [40]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [41]:
RMSE

np.float64(0.8946386461319648)

In [42]:
from sklearn.linear_model import RidgeCV

In [ ]:
# 1. import RidgeCV
# 2. Choose your alphas, and choose your scoring,
# 3.  Let it do its work. 

ridge_CV_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [60]:
ridge_CV_model.fit(X_train, y_train)

,alphas,"(0.1, ...)"
,fit_intercept,True
,scoring,'neg_mean_absolute_error'
,cv,None
,gcv_mode,None
,store_cv_results,False
,alpha_per_target,False


In [54]:
ridge_CV_model.alpha_

np.float64(0.1)

In [55]:
from sklearn.metrics import get_scorer_names


In [61]:
get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'd2_absolute_error_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_max_error',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'neg_root_mean_squared_log_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 're

In [62]:
test_predictions = ridge_CV_model.predict(X_test)

In [63]:
MAE = mean_absolute_error(y_test, test_predictions)

In [64]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [65]:
MAE

0.42737748843375084

In [ ]:
RMSE #Here by using the Rigde regression, we found out better RMSE and MAE than before. 

np.float64(0.6180719926926787)

In [67]:
ridge_CV_model.best_score_

-0.3749223340292961

# LASSO - Least absolute shrinkage and selection operator (L1 regression)

In [71]:
from sklearn.linear_model import LassoCV

In [72]:
LassoCV

sklearn.linear_model._coordinate_descent.LassoCV

In [81]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5) #here we created the model

In [82]:
lasso_cv_model.fit(X_train, y_train)

d:\Programs\Github\data-science-concepts\myenv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(


,eps,0.1
,n_alphas,100
,alphas,'warn'
,fit_intercept,True
,precompute,'auto'
,max_iter,1000
,tol,0.0001
,copy_X,True
,cv,5
,verbose,False
,n_jobs,None


In [83]:
lasso_cv_model.alpha_

np.float64(0.4943070909225831)

In [85]:
test_predictions = lasso_cv_model.predict(X_test)

In [86]:
MAE = mean_absolute_error(y_test, test_predictions)

In [87]:
RMSE =np.sqrt(mean_squared_error(y_test, test_predictions))

In [88]:
MAE

0.6541723161252868

In [ ]:
lasso_cv_model.coef_ #lasso is considering only two features 

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

# Elastic Net :  L1 and L2 Regularization